name: Schedule

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          date "+DATE: %Y/%m/%d%nTIME: %H:%M:%S"
